language: csharp
dist: trusty
mono: none
dotnet: 2.1.2
branches:
 - only:
   - master
   - develop
 
before_script:
 - dotnet restore
    
script:
 - dotnet build TokenManager/TokenManager.csproj # token manager web api project
 - dotnet build UnitTests/UnitTests.csproj # token manager unit tests project