language: csharp
dist: trusty
mono: none
dotnet: 2.1.2
branches:
 - only:
   - master
   - develop
 
before_script:
 - dotnet restore TokenManager/TokenManager.csproj
 - dotnet restore UnitTests/UnitTests.csproj
    
script:
 - dotnet build TokenManager/TokenManager.csproj
 - dotnet build UnitTests/UnitTests.csproj